### ISSUE TITLE
经常会search page error

### ISSUE THREAD

**Issue by dawnli139** [izachwei/12306#1]
![image](https://github.com/izachwei/12306/assets/51946856/1eb374e3-129e-407b-aca1-482eca96010b)
![image](https://github.com/izachwei/12306/assets/51946856/b7c3aa47-0666-45d5-aed7-0e5e91aa6816)

**Comment by dawnli139** [comment]
就是一阵一阵的

**Comment by izachwei** [comment]
> 就是一阵一阵的

这是12306网站本身的限流，之前考虑到这种情况，做了异常处理（刷新页面，重新走买票流程）。

**Comment by izachwei** [comment]
> 就是一阵一阵的

这是12306网站本身的限流，之前考虑到这种情况，做了异常处理（刷新页面，重新走买票流程）。

**Comment by dawnli139** [comment]
刷新是要隔一阵子才能恢复正常嘛，我这刷新经常卡很久才能恢复

**Comment by izachwei** [comment]
> 刷新是要隔一阵子才能恢复正常嘛，我这刷新经常卡很久才能恢复

目前不确定是因为抢票程序请求过于频繁导致的IP限流，还是12306本身网站的整体限流，后面看看针对优化。

**Comment by dawnli139** [comment]
好嘞，谢谢哥~

**Comment by SAuP51** [comment]
明明有票，怎么显示无余票呀
