### ISSUE TITLE
一直显示无余票

### ISSUE THREAD

**Issue by SAuP51** [izachwei/12306#2]
明明有票，怎么一直显示无余票呀

**Comment by izachwei** [comment]
发下你的配置文件呢[startup.properties](https://github.com/izachwei/12306/blob/main/src%2Fmain%2Fresources%2Fdata%2F12306%2Fstartup.properties)？请确认你的购票配置填写正确，例如：trainNumber

**Comment by SAuP51** [comment]
问题我已经解决了，配置文件里面，一等座和二等座（O,M）必须都要写上。单独只填一个二等座（O）就会一直显示无余票。昨天晚上研究了好久才发现这个问题。
