### ISSUE TITLE
进入到了下单界面，选择人员的时候就弹出去又重新执行

### ISSUE THREAD

**Issue by DDDWY** [izachwei/12306#5]
控制台报错：
INFO ] 2023-09-22 14:57:08.988 [main] WebDriverManager - Using chromedriver 114.0.5735.90 (resolved driver for Chrome 116)
[INFO ] 2023-09-22 14:57:09.032 [main] WebDriverManager - Exporting webdriver.chrome.driver as /Users/a1/.cache/selenium/chromedriver/mac64/114.0.5735.90/chromedriver
[INFO ] 2023-09-22 14:57:09.093 [main] BrowserFactory - chrome option:
9月 22, 2023 2:57:11 下午 org.openqa.selenium.devtools.CdpVersionFinder findNearestMatch
警告: Unable to find an exact match for CDP version 117, so returning the closest version found: 116
[ERROR] 2023-09-22 14:57:33.186 [main] Ticket12306Test - stale element reference: stale element not found
  (Session info: chrome=117.0.5938.92)
For documentation on this error, please visit: https://www.selenium.dev/documentation/webdriver/troubleshooting/errors#stale-element-reference-exception
Build info: version: '4.12.1', revision: '8e34639b11'
System info: os.name: 'Mac OS X', os.arch: 'x86_64', os.version: '10.15.7', java.version: '17.0.4.1'
Driver info: org.openqa.selenium.chrome.ChromeDriver
Command: [e3aaeb8575bb090e180004a59a039bec, getElementText {id=EF95B1B5A3B474DB2B43B17BEB44684D_element_297}]
Capabilities {acceptInsecureCerts: false, browserName: chrome, browserVersion: 117.0.5938.92, chrome: {chromedriverVersion: 117.0.5938.92 (67649b10b92b..., userDataDir: /var/folders/c6/1vw5hs0907g...}, fedcm:accounts: true, goog:chromeOptions: {debuggerAddress: localhost:63276}, networkConnectionEnabled: false, pageLoadStrategy: normal, platformName: mac, proxy: Proxy(), se:cdp: ws://localhost:63276/devtoo..., se:cdpVersion: 117.0.5938.92, setWindowRect: true, strictFileInteractability: false, timeouts: {implicit: 0, pageLoad: 300000, script: 30000}, unhandledPromptBehavior: dismiss and notify, webauthn:extension:credBlob: true, webauthn:extension:largeBlob: true, webauthn:extension:minPinLength: true, webauthn:extension:prf: true, webauthn:virtualAuthenticators: true}
Element: [[ChromeDriver: chrome on mac (e3aaeb8575bb090e180004a59a039bec)] -> xpath: //*[@id="queryLeftTable"]/tr]
Session ID: e3aaeb8575bb090e180004a59a039bec
[ERROR] 2023-09-22 14:57:38.869 [main] Ticket12306Test - stale element reference: stale element not found
  (Session info: chrome=117.0.5938.92)
For documentation on this error, please visit: https://www.selenium.dev/documentation/webdriver/troubleshooting/errors#stale-element-reference-exception
Build info: version: '4.12.1', revision: '8e34639b11'
System info: os.name: 'Mac OS X', os.arch: 'x86_64', os.version: '10.15.7', java.version: '17.0.4.1'
Driver info: org.openqa.selenium.chrome.ChromeDriver
Command: [e3aaeb8575bb090e180004a59a039bec, getElementText {id=41666D317B0CC03A6D85E539B2BBC493_element_1069}]
Capabilities {acceptInsecureCerts: false, browserName: chrome, browserVersion: 117.0.5938.92, chrome: {chromedriverVersion: 117.0.5938.92 (67649b10b92b..., userDataDir: /var/folders/c6/1vw5hs0907g...}, fedcm:accounts: true, goog:chromeOptions: {debuggerAddress: localhost:63276}, networkConnectionEnabled: false, pageLoadStrategy: normal, platformName: mac, proxy: Proxy(), se:cdp: ws://localhost:63276/devtoo..., se:cdpVersion: 117.0.5938.92, setWindowRect: true, strictFileInteractability: false, timeouts: {implicit: 0, pageLoad: 300000, script: 30000}, unhandledPromptBehavior: dismiss and notify, webauthn:extension:credBlob: true, webauthn:extension:largeBlob: true, webauthn:extension:minPinLength: true, webauthn:extension:prf: true, webauthn:virtualAuthenticators: true}
Element: [[ChromeDriver: chrome on mac (e3aaeb8575bb090e180004a59a039bec)] -> xpath: //*[@id="queryLeftTable"]/tr]
Session ID: e3aaeb8575bb090e180004a59a039bec
[ERROR] 2023-09-22 14:57:52.121 [main] Ticket12306Test - 无余票

Process finished with exit code 137 (interrupted by signal 9: SIGKILL)

配置文件：
# 始发地
from=深圳
# 目的地
to=东莞
# 出发时间，格式：yyyy-MM-dd
date=2023-09-23
# 车次
trainNumber=C7006
# 座位类型（级别）
# 9：商务座，M：一等座，O：二等座，3：硬卧，4：软卧，1：硬座
lever=O
# 乘坐人（需要在登录的12306账号中存在，请提前添加）
passenger="段伟艺"

**Comment by DDDWY** [comment]
大佬你的谷歌版本是多少

**Comment by DDDWY** [comment]
每次到选择乘车人的界面就会报错 
[ERROR] 2023-09-22 15:09:04.124 [main] Ticket12306Test - stale element reference: stale element not found

**Comment by izachwei** [comment]
你12306账号中，添加了段伟艺这个乘客么？

**Comment by izachwei** [comment]
我谷歌 114 版本

**Comment by DDDWY** [comment]
段伟艺是有的，我的版本是117会不会版本问题

**Comment by izachwei** [comment]
你本地有 edge 浏览器么？试试edge

**Comment by DDDWY** [comment]
![image](https://github.com/izachwei/12306/assets/39432163/931f2101-ed7d-4b0a-9625-67051968181d)
我打印了一下日志

**Comment by DDDWY** [comment]
![image](https://github.com/izachwei/12306/assets/39432163/35c36f84-fa78-4231-b26a-341afb622b16)

**Comment by DDDWY** [comment]
实在不行，我降低下谷歌版本跟你保持一致

**Comment by SAuP51** [comment]
> ![image](https://user-images.githubusercontent.com/39432163/269861462-931f2101-ed7d-4b0a-9625-67051968181d.png) 我打印了一下日志

你这个问题我昨天晚上也遇到过，就是ChromeDriver的版本问题，自己去下117的版本，放到C盘对应目录下

**Comment by DDDWY** [comment]
> > ![image](https://user-images.githubusercontent.com/39432163/269861462-931f2101-ed7d-4b0a-9625-67051968181d.png) 我打印了一下日志
> 
> 你这个问题我昨天晚上也遇到过，就是ChromeDriver的版本问题，自己去下117的版本，放到C盘对应目录下

多谢大佬，那我再试试

**Comment by DDDWY** [comment]
> > ![image](https://user-images.githubusercontent.com/39432163/269861462-931f2101-ed7d-4b0a-9625-67051968181d.png) 我打印了一下日志
> 
> 你这个问题我昨天晚上也遇到过，就是ChromeDriver的版本问题，自己去下117的版本，放到C盘对应目录下

大佬，你的117版本在哪里下载的，能给下链接吗

**Comment by chenkai1121** [comment]
> > > ![image](https://user-images.githubusercontent.com/39432163/269861462-931f2101-ed7d-4b0a-9625-67051968181d.png) 我打印了一下日志
> > 
> > 
> > 你这个问题我昨天晚上也遇到过，就是ChromeDriver的版本问题，自己去下117的版本，放到C盘对应目录下
> 
> 大佬，你的117版本在哪里下载的，能给下链接吗

https://edgedl.me.gvt1.com/edgedl/release2/chrome/munlhn4fskwwv3tyzmkvt4ifa4_117.0.5938.92/117.0.5938.92_chrome_installer.exe

**Comment by DDDWY** [comment]
> > > > ![image](https://user-images.githubusercontent.com/39432163/269861462-931f2101-ed7d-4b0a-9625-67051968181d.png) 我打印了一下日志
> > > 
> > > 
> > > 你这个问题我昨天晚上也遇到过，就是ChromeDriver的版本问题，自己去下117的版本，放到C盘对应目录下
> > 
> > 
> > 大佬，你的117版本在哪里下载的，能给下链接吗
> 
> https://edgedl.me.gvt1.com/edgedl/release2/chrome/munlhn4fskwwv3tyzmkvt4ifa4_117.0.5938.92/117.0.5938.92_chrome_installer.exe

谢谢大佬，不知道是不是因为我这边是mac的原因，还是不行

**Comment by DDDWY** [comment]
> > > > > ![image](https://user-images.githubusercontent.com/39432163/269861462-931f2101-ed7d-4b0a-9625-67051968181d.png) 我打印了一下日志
> > > > 
> > > > 
> > > > 你这个问题我昨天晚上也遇到过，就是ChromeDriver的版本问题，自己去下117的版本，放到C盘对应目录下
> > > 
> > > 
> > > 大佬，你的117版本在哪里下载的，能给下链接吗
> > 
> > 
> > https://edgedl.me.gvt1.com/edgedl/release2/chrome/munlhn4fskwwv3tyzmkvt4ifa4_117.0.5938.92/117.0.5938.92_chrome_installer.exe
> 
> 谢谢大佬，不知道是不是因为我这边是mac的原因，还是不行

找到原因了，是因为界面跳转到下单，而TicketListPage类里面的ticketList还在循环，导致页面更新元素已经找不到了，需要增加最外层的break；
![image](https://github.com/izachwei/12306/assets/39432163/5144379d-f08a-426a-87ed-f91721a72308)

**Comment by izachwei** [comment]
general.properties 
![image](https://github.com/izachwei/12306/assets/37742706/59dc8016-d8e9-4e63-b17e-42ec5fca85f0)
browser 可自定义浏览器
browserVersion 自定义浏览器版本

**Comment by DDDWY** [comment]
> general.properties ![image](https://user-images.githubusercontent.com/37742706/269907190-59dc8016-d8e9-4e63-b17e-42ec5fca85f0.png) browser 可自定义浏览器 browserVersion 自定义浏览器版本

多谢大佬，我这边已经解决啦
