### ISSUE TITLE
特地选了一个有票的车次，但是总是打印无余票

### ISSUE THREAD

**Issue by JoeyWei1** [izachwei/12306#6]
# 始发地
from=南宁东
# 目的地
to=贵港
# 出发时间，格式：yyyy-MM-dd
date=2023-10-05
# 车次
trainNumber=D8393
# 座位类型（级别）
# 9：商务座，M：一等座，O：二等座，3：硬卧，4：软卧，1：硬座
lever=O,M
# 乘坐人（需要在登录的12306账号中存在，请提前添加）
passenger=韦贵劲

**Comment by SAuP51** [comment]
> # 始发地
> from=南宁东
> 
> # 目的地
> to=贵港
> 
> # 出发时间，格式：yyyy-MM-dd
> date=2023-10-05
> 
> # 车次
> trainNumber=D8393
> 
> # 座位类型（级别）
> # 9：商务座，M：一等座，O：二等座，3：硬卧，4：软卧，1：硬座
> lever=O,M
> 
> # 乘坐人（需要在登录的12306账号中存在，请提前添加）
> passenger=韦贵劲

配置文件里面，lever是写的“lever=O,M”还是“lever=O”，如果是后者的会出现有票打印无余票的情况

**Comment by JoeyWei1** [comment]
O,M

**Comment by JoeyWei1** [comment]
写的是O,M

**Comment by izachwei** [comment]
fixed

**Comment by izachwei** [comment]
fixed
